# fly.toml app configuration file generated for ifsp-alert-bot-aya on 2026-02-11T15:23:52-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ifsp-alert-bot-aya'
primary_region = 'gru'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '3001'

[[mounts]]
  source = 'dados_bot'
  destination = '/app/dados_bot'

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']


